version: "3.8"

volumes:
  minio: null

services:
  minio:
    image: minio/minio:RELEASE.2021-09-09T21-37-07Z
    command: server /data --console-address ":9001"
    env_file:
      - .minio.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data